export const dynamic = 'force-dynamic';

import type { Metadata } from 'next';
import PageShell, { SectionHeading, Body, Strong, BodyLink } from '@/components/PageShell';

export const metadata: Metadata = {
  title: 'Privacy — Ishin',
  description:
    'How Ishin handles your data: no ads, no data selling, no tracking cookies. Your messages are used to produce your translation — nothing else.',
};

export default function PrivacyPage() {
  return (
    <PageShell title="Privacy" subtitle="Last updated 19 July 2026">
      <SectionHeading>The short version</SectionHeading>
      <Body>
        Ishin has no ads, sells no data, and uses no tracking cookies. Your messages are used to
        produce your translation — nothing else. Delete your account and your data goes with it.
      </Body>

      <SectionHeading>What we collect</SectionHeading>
      <Body>
        <Strong>Account.</Strong> If you sign in, our auth provider (Clerk) gives us your name and
        email so your history can follow you between devices. Guests can use the translator with no
        account at all — guest conversations are never stored.
      </Body>
      <Body>
        <Strong>Saved history.</Strong> Signed-in translations and checks are stored so they appear
        in your feed. Deleting a message deletes the record; deleting your account deletes
        everything.
      </Body>
      <Body>
        <Strong>Waitlist.</Strong> The business waitlist stores the email you enter, anything you
        write in the context field, and your country. We&apos;ll only email you about the launch,
        every email will include an opt-out, and you can ask to be removed at any time.
      </Body>
      <Body>
        <Strong>Analytics.</Strong> We use Cloudflare Web Analytics — cookieless, no personal
        identifiers, no cross-site tracking. The only cookies on ishin.io are the essential sign-in
        session cookies set by Clerk.
      </Body>

      <SectionHeading>How translations work</SectionHeading>
      <Body>
        Your message is sent to Anthropic&apos;s Claude API to generate the translation or
        naturalness check. Under the API terms we use, message content is not used to train models —
        and we never use your messages for training, product research, or anything beyond serving
        your request.
      </Body>

      <SectionHeading>Where your data lives</SectionHeading>
      <Body>
        Ishin is operated from Australia, but the services it&apos;s built on are based in the
        United States — sign-in runs on Clerk, stored history lives in Supabase, the site is hosted
        on Vercel, translations are generated by Anthropic, and analytics run on Cloudflare. Using
        Ishin means your information is processed by these providers in the US.
      </Body>

      <SectionHeading>Your rights</SectionHeading>
      <Body>
        You can ask us for a copy of the personal information we hold about you, ask us to correct
        it, or ask us to delete it — email <BodyLink href="mailto:hello@ishin.io" /> and we&apos;ll
        respond within 30 days. Saved history you can also delete yourself, message by message or
        all at once.
      </Body>

      <SectionHeading>Complaints</SectionHeading>
      <Body>
        If you think we&apos;ve mishandled your information, email us first and we&apos;ll try to
        put it right. If you&apos;re not satisfied with our response, you can complain to the Office
        of the Australian Information Commissioner (
        <BodyLink href="https://www.oaic.gov.au" external />) or your local data protection
        authority.
      </Body>

      <SectionHeading>Contact</SectionHeading>
      <Body>
        Questions, or want your data removed? <BodyLink href="mailto:hello@ishin.io" />.
      </Body>
    </PageShell>
  );
}
